## ADA BOOST WITH SPAMBASE DATA SET

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"
column_names = [f"word_freq_{i}" for i in range(48)] + ["char_freq_" + c for c in ";!$#"] + ["capital_run_length_avg", "capital_run_length_longest", "capital_run_length_total", "label"]

In [3]:
data = pd.read_csv(url, header=None, names=column_names)

In [4]:
data.head()

word_freq_0  word_freq_1  word_freq_2  word_freq_3  word_freq_4  \
0.00 0.64         0.64          0.0         0.32         0.00         0.00   
0.21 0.28         0.50          0.0         0.14         0.28         0.21   
0.06 0.00         0.71          0.0         1.23         0.19         0.19   
0.00 0.00         0.00          0.0         0.63         0.00         0.31   
     0.00         0.00          0.0         0.63         0.00         0.31   

           word_freq_5  word_freq_6  word_freq_7  word_freq_8  word_freq_9  \
0.00 0.64         0.00         0.00         0.00         0.00         0.64   
0.21 0.28         0.07         0.00         0.94         0.21         0.79   
0.06 0.00         0.12         0.64         0.25         0.38         0.45   
0.00 0.00         0.63         0.31         0.63         0.31         0.31   
     0.00         0.63         0.31         0.63         0.31         0.31   

           ...  word_freq_46  word_freq_47  char_freq_;  char_freq_!  \
0.00 0.64  ...          0.00         0.000          0.0        0.778   
0.21 0.28  ...          0.00         0.132          0.0        0.372   
0.06 0.00  ...          0.01         0.143          0.0        0.276   
0.00 0.00  ...          0.00         0.137          0.0        0.137   
     0.00  ...          0.00         0.135          0.0        0.135   

           char_freq_$  char_freq_#  capital_run_length_avg  \
0.00 0.64        0.000        0.000                   3.756   
0.21 0.28        0.180        0.048                   5.114   
0.06 0.00        0.184        0.010                   9.821   
0.00 0.00        0.000        0.000                   3.537   
     0.00        0.000        0.000                   3.537   

           capital_run_length_longest  capital_run_length_total  label  
0.00 0.64                          61                       278      1  
0.21 0.28                         101                      1028      1  
0.06 0.00                         485                      2259      1  
0.00 0.00                          40                       191      1  
     0.00                          40                       191      1  

[5 rows x 56 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4601 entries, (0.0, 0.64) to (0.0, 0.0)
Data columns (total 56 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   word_freq_0                 4601 non-null   float64
 1   word_freq_1                 4601 non-null   float64
 2   word_freq_2                 4601 non-null   float64
 3   word_freq_3                 4601 non-null   float64
 4   word_freq_4                 4601 non-null   float64
 5   word_freq_5                 4601 non-null   float64
 6   word_freq_6                 4601 non-null   float64
 7   word_freq_7                 4601 non-null   float64
 8   word_freq_8                 4601 non-null   float64
 9   word_freq_9                 4601 non-null   float64
 10  word_freq_10                4601 non-null   float64
 11  word_freq_11                4601 non-null   float64
 12  word_freq_12                4601 non-null   float64
 13  word_freq_13     

In [6]:
data['label'].unique()

array([1, 0], dtype=int64)

In [7]:
x = data.iloc[:,:-1] ## all features
y = data.iloc[:,-1] ## spam or not(1 or 0)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y, random_state =42, test_size=0.2)

In [10]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((3680, 55), (3680,), (921, 55), (921,))

In [11]:
## scaling

from sklearn.preprocessing import StandardScaler

In [12]:
scaled = StandardScaler()

scaled_x_train = scaled.fit_transform(x_train)
sclaed_x_test = scaled.transform(x_test)

In [13]:
from sklearn.ensemble import AdaBoostClassifier

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
basemodel = DecisionTreeClassifier(max_depth=1)

In [16]:
adaboost = AdaBoostClassifier(base_estimator = basemodel, n_estimators = 50, learning_rate = 1, random_state=42)

In [17]:
adaboost

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1, random_state=42)

In [18]:
adaboost.fit(x_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1, random_state=42)

In [19]:
y_pred = adaboost.predict(x_test)

In [20]:
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
print("AdaBoost Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

AdaBoost Accuracy: 0.9402823018458197
Confusion Matrix:
 [[503  28]
 [ 27 363]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.95      0.95       531
           1       0.93      0.93      0.93       390

    accuracy                           0.94       921
   macro avg       0.94      0.94      0.94       921
weighted avg       0.94      0.94      0.94       921



In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
y_pred_dt = dt_model.predict(x_test)

# Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(x_train, y_train)
y_pred_rf = rf_model.predict(x_test)

# Logistic Regression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(x_train, y_train)
y_pred_lr = lr_model.predict(x_test)

# Print accuracy scores for comparison
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))


Decision Tree Accuracy: 0.9087947882736156
Random Forest Accuracy: 0.9554831704668838
Logistic Regression Accuracy: 0.9207383279044516
